# Generated by Django 4.0.6 on 2022-08-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='', verbose_name='Фаил')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('img', models.ImageField(upload_to='images', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
