# Generated by Django 4.0.6 on 2022-08-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apps',
            options={'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
        migrations.AddField(
            model_name='apps',
            name='video',
            field=models.FileField(default=None, upload_to='', verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
