# Generated by Django 4.0.6 on 2022-08-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_apps_options_apps_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='Editor_Choice',
            field=models.BooleanField(default=False, verbose_name='Выбор редакции'),
            preserve_default=False,
        ),
    ]
