# Generated by Django 4.0.6 on 2022-08-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='', verbose_name='Фаил')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('img', models.ImageField(upload_to='images', verbose_name='Иконка')),
                ('video', models.FileField(upload_to='', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterField(
            model_name='apps',
            name='Editor_Choice',
            field=models.BooleanField(default=False, verbose_name='Выбор редакции'),
        ),
        migrations.AlterField(
            model_name='apps',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
